version: "3.9"
services:
  db-server:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - db-server-data:/var/lib/postgresql/dev-data
    hostname: db-server
volumes:
  db-server-data:
