# fly.toml app configuration file generated for radio-chat-backend on 2023-08-08T08:21:23-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "radio-chat-backend"
primary_region = "gdl"

[build]

[http_service]
  internal_port = 5050
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
